export const CURRENT_USER = 'CURRENT_USER'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAILURE = 'CURRENT_USER_FAILURE'

export const USER = 'USER'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAILURE = 'USER_FAILURE'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const SET_DRAWER = 'SET_DRAWER'
export const SET_POST_DIALOG = ' SET_POST_DIALOG'
export const USERS_LIST_END = 'USERS_LIST_END'
export const POSTS_LIST_END = 'POSTS_LIST_END'
export const UPLOAD_PHOTOS = 'UPLOAD_PHOTOS'
export const DELETE_PREVIEW = 'DELETE_PREVIEW'
export const CHAT_ROOMS_LIST_END = 'CHAT_ROOMS_LIST_END'
export const MESSAGES_LIST_END = 'MESSAGES_LIST_END'

export const REGISTRAION = 'REGISTRAION'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRAION_FAILURE = 'REGISTRAION_FAILURE'

export const USERS_LIST = 'USERS_LIST'
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS'
export const USERS_LIST_FAILURE = 'USERS_LIST_FAILURE'

export const USER_UPDATE = 'USER_UPDATE'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'

export const POSTS_LIST = 'POSTS_LIST'
export const POSTS_LIST_SUCCESS = 'POSTS_LIST_SUCCESS'
export const POSTS_LIST_FAILURE = 'POSTS_LIST_FAILURE'

export const POST_CREATE = 'POST_CREATE'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAILURE = 'POST_CREATE_FAILURE'

export const CHAT_ROOMS_LIST = 'CHAT_ROOMS_LIST'
export const CHAT_ROOMS_LIST_SUCCESS = 'CHAT_ROOMS_LIST_SUCCESS'
export const CHAT_ROOMS_LIST_FAILURE = 'CHAT_ROOMS_LIST_FAILURE'

export const CHAT_ROOM = 'CHAT_ROOM'
export const CHAT_ROOM_SUCCESS = 'CHAT_ROOM_SUCCESS'
export const CHAT_ROOM_FAILURE = 'CHAT_ROOM_FAILURE'

export const CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM'
export const CREATE_CHAT_ROOM_SUCCESS = 'CREATE_CHAT_ROOM_SUCCESS'
export const CREATE_CHAT_ROOM_FAILURE = 'CREATE_CHAT_ROOM_FAILURE'

export const MESSAGES_LIST = 'MESSAGES_LIST'
export const MESSAGES_LIST_SUCCESS = 'MESSAGES_LIST_SUCCESS'
export const MESSAGES_LIST_FAILURE = 'MESSAGES_LIST_FAILURE'

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'

export const SET_USERS_FILTER = 'SET_USERS_FILTER'
